physicaliqa:
  roberta:
    roberta-large:
      lr: 5e-6
      batch_size: 8
    large_roberta:
      lr: 1e-5
      batch_size: 16
    lm_with_dp_graphs_gtn1L_fcn_dpbatch1_multitask_beta_0p001_10000_w_cn_all_cs_v1:
      lr: 5e-6
      batch_size: 4
      dropout: 0.1
      accumulate_grad_batches: 2
      max_nb_epochs: 4
    lm_with_dp_graphs_gtn1L_fcn_dpbatch1_multitask_beta_0p001_10000:
      lr: 5e-6
      batch_size: 4
      dropout: 0.1
      accumulate_grad_batches: 2
      max_nb_epochs: 3
    lm_with_dp_graphs_gtn1L_fcn_dpbatch1_multitask_beta_0p001_10000_contd:
      lr: 5e-6
      batch_size: 4
      dropout: 0.1
      accumulate_grad_batches: 2
      max_nb_epochs: 4
    lm_with_dp_graphs_gtn1L_fcn_dpbatch1_multitask_beta_0p001_10000_bc:
      lr: 5e-6
      batch_size: 4
      dropout: 0
      accumulate_grad_batches: 2
      max_nb_epochs: 4
    lm_with_dp_graphs_gtn1L_fcn_dpbatch1_multitask_beta_0p001_10000_bc2:
      lr: 1e-6
      batch_size: 4
      dropout: 0
      accumulate_grad_batches: 2
      max_nb_epochs: 5
    lm_with_dp_graphs_gtn1L_fcn_dpbatch1_multitask_beta_0p001_12000:
      lr: 5e-6
      batch_size: 4
      dropout: 0.1
      accumulate_grad_batches: 2
      max_nb_epochs: 6
    mutimodal_lm_large_finetune_cc_cn_dc_30000:
      lr: 5e-6
      batch_size: 4
      dropout: 0.1
      accumulate_grad_batches: 4
    baseline:
      lr: 5e-6
      batch_size: 8
      dropout: 0.1
      max_nb_epochs: 3
    baseline2:
      lr: 5e-6
      batch_size: 8
      dropout: 0.1
      max_nb_epochs: 3
    baseline3:
      lr: 5e-6
      batch_size: 8
      dropout: 0
      max_nb_epochs: 3
    baseline4:
      lr: 5e-6
      batch_size: 16
      dropout: 0.5
      max_nb_epochs: 3
    baseline5:
      lr: 5e-6
      batch_size: 16
      dropout: 0.5
      max_nb_epochs: 3
    baseline6:
      lr: 5e-6
      batch_size: 16
      dropout: 0
      max_nb_epochs: 3
    baseline7:
      lr: 5e-6
      batch_size: 16
      dropout: 0
      max_nb_epochs: 3
    baseline8:
      lr: 5e-6
      batch_size: 16
      dropout: 0.1
      max_nb_epochs: 3
    baseline9:
      lr: 5e-6
      batch_size: 16
      dropout: 0.1
      max_nb_epochs: 3
    baseline_w_cn_all_cs_v1:
      lr: 5e-6
      batch_size: 4
      dropout: 0.1
      accumulate_grad_batches: 2
      max_nb_epochs: 4
    baseline_w_cn_all_cs_v1_gac_4:
      lr: 5e-6
      batch_size: 4
      dropout: 0.1
      accumulate_grad_batches: 4
      max_nb_epochs: 4
    baseline_w_cn_all_cs_v1_gac_4_20k:
      lr: 5e-6
      batch_size: 4
      dropout: 0.1
      accumulate_grad_batches: 4
      max_nb_epochs: 4
    baseline_w_cn_all_cs_v1_gac_4_20k_contd:
      lr: 5e-6
      batch_size: 4
      dropout: 0.1
      accumulate_grad_batches: 4
      max_nb_epochs: 5
    baseline_w_cn_all_cs_v1_contd_30k:
      lr: 5e-6
      batch_size: 4
      dropout: 0.1
      accumulate_grad_batches: 2
      max_nb_epochs: 5
    baseline_w_cn_all_cs_v1_contd2_30k:
      lr: 1e-6
      batch_size: 4
      dropout: 0
      accumulate_grad_batches: 2
      max_nb_epochs: 6
    baseline_w_cn_all_cs_v1_contd_v1:
      lr: 5e-6
      batch_size: 4
      dropout: 0.1
      accumulate_grad_batches: 2
      max_nb_epochs: 5
    baseline_w_cn_all_cs_v1_contd_maxlen256_contd2:
      lr: 1e-6
      batch_size: 4
      dropout: 0
      accumulate_grad_batches: 2
      max_nb_epochs: 6
      max_seq_len: 256
    baseline_w_cn_all_cs_v1_contd_maxlen256:
      lr: 5e-6
      batch_size: 4
      dropout: 0.1
      accumulate_grad_batches: 2
      max_nb_epochs: 5
      max_seq_len: 256
    baseline_w_cn_all_cs_v1_contd2_v1:
      lr: 1e-6
      batch_size: 4
      dropout: 0
      accumulate_grad_batches: 2
      max_nb_epochs: 6
    baseline_w_cn_all_cs_v1_contd2_maxlen256:
      lr: 1e-6
      batch_size: 4
      dropout: 0
      accumulate_grad_batches: 2
      max_nb_epochs: 6
      max_seq_len: 256
    baseline_w_cn_all_cs_v1_contd2_maxlen256_v2:
      lr: 1e-6
      batch_size: 4
      dropout: 0.1
      accumulate_grad_batches: 2
      max_nb_epochs: 6
      max_seq_len: 256
    baseline_w_cn_all_cs_v1_singlefc:
      lr: 5e-6
      batch_size: 4
      dropout: 0.1
      accumulate_grad_batches: 2
      max_nb_epochs: 4
    baseline_w_cn_all_cs_v1_maxlen256:
      lr: 5e-6
      batch_size: 4
      dropout: 0.1
      accumulate_grad_batches: 2
      max_nb_epochs: 4
      max_seq_len: 256
    baseline_w_cn_all_cs_v2:
      lr: 5e-6
      batch_size: 4
      dropout: 0.5
      accumulate_grad_batches: 1
    baseline_w_cn_all_cs_v3:
      lr: 5e-6
      batch_size: 8
      dropout: 0.5
      accumulate_grad_batches: 1
    baseline_w_cn_all_cs_v3_bz_8_gac_4:
      lr: 5e-6
      batch_size: 8
      dropout: 0.5
      accumulate_grad_batches: 4
    baseline_w_cn_all_cs_v3_bz_8_gac_4_20k:
      lr: 5e-6
      batch_size: 8
      dropout: 0.5
      accumulate_grad_batches: 4
    baseline_w_cn_all_cs_v3_contd:
      lr: 1e-6
      batch_size: 8
      dropout: 0.1
      accumulate_grad_batches: 1
      max_nb_epochs: 4
    baseline_w_cn_all_cs_60k:
      lr: 5e-6
      batch_size: 4
      dropout: 0.5
      accumulate_grad_batches: 1
    baseline_w_cn_all_cs_v3_single_fc:
      lr: 5e-6
      batch_size: 8
      dropout: 0.5
      accumulate_grad_batches: 1
    baseline_w_cn_all_cs_v3_single_fc_contd_v1:
      lr: 5e-6
      batch_size: 8
      dropout: 0.5
      accumulate_grad_batches: 1
      max_nb_epochs: 4
    baseline_w_cn_all_cs_v3_40k:
      lr: 5e-6
      batch_size: 8
      dropout: 0.5
      accumulate_grad_batches: 1
    multi_large_finetuned_v3_26000_w_cn_all_cs_v1:
      lr: 5e-6
      batch_size: 4
      dropout: 0.1
      accumulate_grad_batches: 2
      max_nb_epochs: 4
    lm_finetuned_wikihow_30000:
      lr: 5e-6
      batch_size: 4
      dropout: 0.1
      accumulate_grad_batches: 2
      max_nb_epochs: 5
    lm_finetuned_wikihow_dc_cc_50000:
      lr: 5e-6
      batch_size: 4
      dropout: 0.1
      accumulate_grad_batches: 2
      max_nb_epochs: 4
    lm_finetuned_wikihow_30000_w_cn_all_cs_v1:
      lr: 5e-6
      batch_size: 4
      dropout: 0.1
      accumulate_grad_batches: 2
      max_nb_epochs: 4
    comet_roberta_singletrip_98:
      lr: 5e-6
      batch_size: 4
      dropout: 0.1
      accumulate_grad_batches: 2
      max_nb_epochs: 4
    comet_roberta_singletrip_5:
      lr: 5e-6
      batch_size: 4
      dropout: 0.1
      accumulate_grad_batches: 2
      max_nb_epochs: 4
    comet_roberta_singletrip_98_w_cn_all_cs_v1:
      lr: 5e-6
      batch_size: 4
      dropout: 0.1
      accumulate_grad_batches: 2
      max_nb_epochs: 4
    roberta_w_cn_comet:
      lr: 5e-6
      batch_size: 1
      dropout: 0.1
      accumulate_grad_batches: 1
      max_nb_epochs: 4
  default:
    seed: 42
    lr: 2e-5
    dropout: 0.5
    batch_size: 32
    max_seq_len: 128
    max_nb_epochs: 3
    initializer_range: 0.02
    weight_decay: 0.0
    warmup_steps: 0
    adam_epsilon: 1e-8
    accumulate_grad_batches: 1
    do_lower_case: false
