alphanli:
  urls:
    - "https://storage.googleapis.com/ai2-mosaic/public/alphanli/alphanli-train-dev.zip"
  task_formula: "[CLS] obs1 [SEP] hyp1|hyp2 [SEP] obs2 [SEP]"
  type_formula: "0 0 0 1 1 0 0"
  label_offset: 1
  num_choices: 2
  file_mapping:
    train:
      train_x: "train.jsonl"
      train_y: "train-labels.lst"
    dev:
      dev_x: "dev.jsonl"
      dev_y: "dev-labels.lst"
snli:
  urls:
    - "https://nlp.stanford.edu/projects/snli/snli_1.0.zip"
  task_formula: "[CLS] sentence1 [SEP] sentence2 [SEP]"
  type_formula: "0 0 0 1 1"
  label_formula: "gold_label"
  label_offset: 0
  num_choices: 1
  label_transform:
    neutral: 0
    entailment: 1
    contradiction: 2
    "-": 3
  output_dimension: 4
  file_mapping:
    train:
      train_x: "snli_1.0/snli_1.0_train.jsonl"
      train_y: "snli_1.0/snli_1.0_train.jsonl"
    dev:
      dev_x: "snli_1.0/snli_1.0_dev.jsonl"
      dev_y: "snli_1.0/snli_1.0_dev.jsonl"
hellaswag:
  urls:
    - "https://storage.googleapis.com/ai2-mosaic/public/hellaswag/hellaswag-train-dev.zip"
  task_formula: "[CLS] ctx [SEP] ending_options [SEP]"
  type_formula: "0 0 0 1 1"
  label_offset: 0
  num_choices: 4
  file_mapping:
    train:
      train_x: "hellaswag-train-dev/train.jsonl"
      train_y: "hellaswag-train-dev/train-labels.lst"
    dev:
      dev_x: "hellaswag-train-dev/valid.jsonl"
      dev_y: "hellaswag-train-dev/valid-labels.lst"
physicaliqa:
  urls:
    - "https://storage.googleapis.com/ai2-mosaic/public/physicaliqa/physicaliqa-train-dev.zip"
  task_formula: "[CLS] goal [SEP] sol1|sol2 [SEP]"
  type_formula: "0 0 0 1 1"
  label_offset: 0
  num_choices: 2
  file_mapping:
    train:
      train_x: "physicaliqa-train-dev/train.jsonl"
      train_y: "physicaliqa-train-dev/train-labels.lst"
    dev:
      dev_x: "physicaliqa-train-dev/dev.jsonl"
      dev_y: "physicaliqa-train-dev/dev-labels.lst"
socialiqa:
  urls:
    - "https://storage.googleapis.com/ai2-mosaic/public/socialiqa/socialiqa-train-dev.zip"
  task_formula: "[CLS] context [SEP] question [SEP] answerA|answerB|answerC [SEP]"
  type_formula: "0 0 0 0 0 1 1"
  label_offset: 1
  num_choices: 3
  file_mapping:
    train:
      train_x: "socialiqa-train-dev/train.jsonl"
      train_y: "socialiqa-train-dev/train-labels.lst"
    dev:
      dev_x: "socialiqa-train-dev/dev.jsonl"
      dev_y: "socialiqa-train-dev/dev-labels.lst"
vcrqa:
  urls:
    - "https://storage.googleapis.com/ai2-mosaic/public/vcr/train.tar.gz"
    - "https://storage.googleapis.com/ai2-mosaic/public/vcr/val.tar.gz"
  pretokenized: true
  task_formula: "[CLS] question [SEP] answer_choices [SEP]"
  type_formula: "0 0 0 1 1"
  label_formula: "answer_label"
  label_offset: 0
  num_choices: 4
  file_mapping:
    train:
      train_x: "train/qa.jsonl"
      train_y: "train/labels.jsonl"
    dev:
      dev_x: "val/qa.jsonl"
      dev_y: "val/labels.jsonl"
vcrqr:
  urls:
    - "https://storage.googleapis.com/ai2-mosaic/public/vcr/train.tar.gz"
    - "https://storage.googleapis.com/ai2-mosaic/public/vcr/val.tar.gz"
  pretokenized: true
  task_formula: "[CLS] question [SEP] rationale_choices [SEP]"
  type_formula: "0 0 0 1 1"
  label_formula: "rationale_label"
  label_offset: 0
  num_choices: 4
  file_mapping:
    train:
      train_x: "train/qar.jsonl"
      train_y: "train/labels.jsonl"
    dev:
      dev_x: "val/qar.jsonl"
      dev_y: "val/labels.jsonl"
cn_all_cs:
  urls:
    - "https://storage.googleapis.com/ai2-mosaic/public/cn_all_cs/cn_all_cs-train-dev.zip"
  task_formula: "[CLS] e1 [SEP] e2 [SEP] sol1|sol2|sol3|sol4|sol5|sol6|sol7 [SEP]"
  type_formula: "0 0 0 0 0 1 1"
  label_offset: 0
  num_choices: 7
  file_mapping:
    train:
      train_x: "cn_all_cs-train-dev/train.jsonl"
      train_y: "cn_all_cs-train-dev/train-labels.lst"
    dev:
      dev_x: "cn_all_cs-train-dev/dev.jsonl"
      dev_y: "cn_all_cs-train-dev/dev-labels.lst"
cn_all_cs_30k:
  urls:
    - "https://storage.googleapis.com/ai2-mosaic/public/cn_all_cs_30k/cn_all_cs_30k-train-dev.zip"
  task_formula: "[CLS] e1 [SEP] e2 [SEP] sol1|sol2|sol3|sol4|sol5|sol6|sol7 [SEP]"
  type_formula: "0 0 0 0 0 1 1"
  label_offset: 0
  num_choices: 7
  file_mapping:
    train:
      train_x: "cn_all_cs_30k-train-dev/train.jsonl"
      train_y: "cn_all_cs_30k-train-dev/train-labels.lst"
    dev:
      dev_x: "cn_all_cs_30k-train-dev/dev.jsonl"
      dev_y: "cn_all_cs_30k-train-dev/dev-labels.lst"
atomic_attr_qa:
  urls:
    - "https://storage.googleapis.com/ai2-mosaic/public/atomic_attr_qa/atomic_attr_qa-train-dev.zip"
  task_formula: "[CLS] content [SEP] question [SEP] answerA|answerB|answerC [SEP]"
  type_formula: "0 0 0 0 0 1 1"
  label_offset: 1
  num_choices: 3
  file_mapping:
    train:
      train_x: "atomic_attr_qa-train-dev/train.jsonl"
      train_y: "atomic_attr_qa-train-dev/train-labels.lst"
    dev:
      dev_x: "atomic_attr_qa-train-dev/dev.jsonl"
      dev_y: "atomic_attr_qa-train-dev/dev-labels.lst"
atomic_temporal_qa:
  urls:
    - "https://storage.googleapis.com/ai2-mosaic/public/atomic_temporal_qa/atomic_temporal_qa-train-dev.zip"
  task_formula: "[CLS] content [SEP] question [SEP] answerA|answerB|answerC [SEP]"
  type_formula: "0 0 0 0 0 1 1"
  label_offset: 1
  num_choices: 3
  file_mapping:
    train:
      train_x: "atomic_temporal_qa-train-dev/train.jsonl"
      train_y: "atomic_temporal_qa-train-dev/train-labels.lst"
    dev:
      dev_x: "atomic_temporal_qa-train-dev/dev.jsonl"
      dev_y: "atomic_temporal_qa-train-dev/dev-labels.lst"
atomic_which_one_qa:
  urls:
    - "https://storage.googleapis.com/ai2-mosaic/public/atomic_which_one_qa/atomic_which_one_qa-train-dev.zip"
  task_formula: "[CLS] content [SEP] question [SEP] answerA|answerB|answerC [SEP]"
  type_formula: "0 0 0 0 0 1 1"
  label_offset: 1
  num_choices: 3
  file_mapping:
    train:
      train_x: "atomic_which_one_qa-train-dev/train.jsonl"
      train_y: "atomic_which_one_qa-train-dev/train-labels.lst"
    dev:
      dev_x: "atomic_which_one_qa-train-dev/dev.jsonl"
      dev_y: "atomic_which_one_qa-train-dev/dev-labels.lst"
atomic_attr_qa_random_name:
  urls:
    - "https://storage.googleapis.com/ai2-mosaic/public/atomic_attr_qa_random_name/atomic_attr_qa_random_name-train-dev.zip"
  task_formula: "[CLS] content [SEP] question [SEP] answerA|answerB|answerC [SEP]"
  type_formula: "0 0 0 0 0 1 1"
  label_offset: 1
  num_choices: 3
  file_mapping:
    train:
      train_x: "atomic_attr_qa_random_name-train-dev/train.jsonl"
      train_y: "atomic_attr_qa_random_name-train-dev/train-labels.lst"
    dev:
      dev_x: "atomic_attr_qa_random_name-train-dev/dev.jsonl"
      dev_y: "atomic_attr_qa_random_name-train-dev/dev-labels.lst"
socialiqa_X:
  urls:
    - "https://storage.googleapis.com/ai2-mosaic/public/socialiqa_X/socialiqa_X-train-dev.zip"
  task_formula: "[CLS] context [SEP] question [SEP] answerA|answerB|answerC [SEP]"
  type_formula: "0 0 0 0 0 1 1"
  label_offset: 1
  num_choices: 3
  file_mapping:
    train:
      train_x: "socialiqa_X-train-dev/train.jsonl"
      train_y: "socialiqa_X-train-dev/train-labels.lst"
    dev:
      dev_x: "socialiqa_X-train-dev/dev.jsonl"
      dev_y: "socialiqa_X-train-dev/dev-labels.lst"
physicaliqa_p25_v1:
  urls:
    - "https://storage.googleapis.com/ai2-mosaic/public/physicaliqa/physicaliqa_p25_v1-train-dev.zip"
  task_formula: "[CLS] goal [SEP] sol1|sol2 [SEP]"
  type_formula: "0 0 0 1 1"
  label_offset: 0
  num_choices: 2
  file_mapping:
    train:
      train_x: "physicaliqa_p25_v1-train-dev/train.jsonl"
      train_y: "physicaliqa_p25_v1-train-dev/train-labels.lst"
    dev:
      dev_x: "physicaliqa_p25_v1-train-dev/dev.jsonl"
      dev_y: "physicaliqa_p25_v1-train-dev/dev-labels.lst"
physicaliqa_p50_v1:
  urls:
    - "https://storage.googleapis.com/ai2-mosaic/public/physicaliqa/physicaliqa_p50_v1-train-dev.zip"
  task_formula: "[CLS] goal [SEP] sol1|sol2 [SEP]"
  type_formula: "0 0 0 1 1"
  label_offset: 0
  num_choices: 2
  file_mapping:
    train:
      train_x: "physicaliqa_p50_v1-train-dev/train.jsonl"
      train_y: "physicaliqa_p50_v1-train-dev/train-labels.lst"
    dev:
      dev_x: "physicaliqa_p50_v1-train-dev/dev.jsonl"
      dev_y: "physicaliqa_p50_v1-train-dev/dev-labels.lst"
physicaliqa_p75_v1:
  urls:
    - "https://storage.googleapis.com/ai2-mosaic/public/physicaliqa/physicaliqa_p75_v1-train-dev.zip"
  task_formula: "[CLS] goal [SEP] sol1|sol2 [SEP]"
  type_formula: "0 0 0 1 1"
  label_offset: 0
  num_choices: 2
  file_mapping:
    train:
      train_x: "physicaliqa_p75_v1-train-dev/train.jsonl"
      train_y: "physicaliqa_p75_v1-train-dev/train-labels.lst"
    dev:
      dev_x: "physicaliqa_p75_v1-train-dev/dev.jsonl"
      dev_y: "physicaliqa_p75_v1-train-dev/dev-labels.lst"
social_before_after:
  urls:
    - "https://storage.googleapis.com/ai2-mosaic/public/social_before_after/social_before_after-train-dev.zip"
  task_formula: "[CLS] context|beforeA|beforeB|beforeC [SEP] afterA|afterB|afterC|context [SEP]"
  type_formula: "0 0 0 1 1" # later make it q: 0 a: 1
  label_offset: 1
  num_choices: 3
  file_mapping:
    train:
      train_x: "social_before_after-train-dev/train.jsonl"
      train_y: "social_before_after-train-dev/train-labels.lst"
    dev:
      dev_x: "social_before_after-train-dev/dev.jsonl"
      dev_y: "social_before_after-train-dev/dev-labels.lst"
physicalbinqa:
  urls:
    - "https://storage.googleapis.com/ai2-mosaic/public/physicalbinqa/physicalbinqa-train-dev.zip"
  task_formula: "[CLS] goal [SEP] sol [SEP]"
  type_formula: "0 0 0 1 1"
  label_offset: 0
  num_choices: 2
  file_mapping:
    train:
      train_x: "physicalbinqa-train-dev/train.jsonl"
      train_y: "physicalbinqa-train-dev/train-labels.lst"
    dev:
      dev_x: "physicalbinqa-train-dev/dev.jsonl"
      dev_y: "physicalbinqa-train-dev/dev-labels.lst"
